version: '3'

volumes:
  local_postgres_data: {}

services:
  postgres:

    image: postgres:12.2

    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:6.2.6
    container_name: redis
    ports:
      - "6379:6379"

  django:
    &django
    build:
      context: .
      dockerfile: infra/dockers/local/app/Dockerfile
    image: hello_world/local/app
    container_name: django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0

    ports:
      - "8008:8008"
    command: /scripts/runserver.sh
